### ISSUE TITLE
It's 2021!

### ISSUE THREAD

**Issue by AkibAzmain** [primis/Apollo#5]
The year in the license is still 2019. Also, consider using a copyleft license like GNU GPLv3 to disallow nonfree distribution and protect user freedom.

**Comment by primis** [comment]
Hi Akib, thank you for staying with the project. The year hasn't been updated because the source code hasn't had much activity since 2019. If the source gets updated to add more features, the license year will increment then. 

As for the license: I chose MIT to allow others to extend and improve my code. I have no qualms if they want to close source their improvements. There are many projects who successfully use non-copyleft licenses that are successful and I feel no reason to GPL my code.
